# ======================================================================
# C-40 / C-43 / A-1 gate batteries (0.3.0)
#
# Referents are EXTERNAL to the engine under test:
#   (i)   goldens generated by installed 0.2.0 on real visibility graphs
#         -- regime 1 must be bit-identical;
#   (ii)  a reference Warshall closure in pure R (independent arithmetic)
#         -- on permuted DAGs the new result must equal the truth, and
#         the raw 0.2.0 motor (still shipped as the inner engine) must
#         disagree with it, which is the defect being repaired;
#   (iii) hand-built condensations for cyclic digraphs;
# plus the two named cases: the 3-cycle 1->2->3->1 and the reversed
# chain 3->2->1, and the property tests for the intents-extents theorem
# (C-43) and the Alexandrov chain constancy on visibility graphs (A-1).
# ======================================================================

# Reference reachability: Warshall closure on a logical matrix.
# Deliberately naive O(n^3); independent of bitsets and of index order.
ref_reach_matrix <- function(adj, n) {
  R <- matrix(FALSE, n, n)
  for (v in seq_len(n)) {
    R[v, v] <- TRUE
    nb <- adj[[v]]
    nb <- nb[nb >= 1 & nb <= n]
    R[v, nb] <- TRUE
  }
  for (k in seq_len(n)) {
    for (i in seq_len(n)) {
      if (R[i, k]) R[i, ] <- R[i, ] | R[k, ]
    }
  }
  R
}

# Reference Alexandrov base: the distinct reachability upsets.
ref_alexandrov_base <- function(adj, n) {
  R <- ref_reach_matrix(adj, n)
  upsets <- lapply(seq_len(n), function(v) which(R[v, ]))
  unique(upsets)
}

# Canonical form for comparing families of sets regardless of order.
canon <- function(sets) {
  sets <- lapply(sets, function(s) sort(as.integer(s)))
  keys <- vapply(sets, paste, character(1), collapse = ",")
  sets[order(keys)]
}

# ----------------------------------------------------------------------
# Battery (i): regime 1 is bit-identical to the 0.2.0 goldens
# ----------------------------------------------------------------------

test_that("index-ordered visibility graphs reproduce the 0.2.0 goldens bit for bit", {
  goldens <- readRDS(test_path("fixtures", "alexandrov_goldens_020.rds"))
  expect_gte(length(goldens), 60L)

  for (case in goldens) {
    new <- generate_alexandrov_topology(
      case$out_adjacency, case$n,
      max_open_sets = if (case$enumerated) 5000L else 0L
    )
    old <- case$golden
    # Every 0.2.0 field, identical to the stored output
    for (f in names(old)) {
      expect_identical(new[[f]], old[[f]],
                       info = sprintf("field '%s', n=%d, %s",
                                      f, case$n, case$graph_type))
    }
    # The new fields say what regime 1 is
    expect_true(new$input_index_ordered)
    expect_true(new$input_acyclic)
    expect_identical(new$collapsed_classes, list())
  }
})

# ----------------------------------------------------------------------
# Battery (ii): permuted DAGs against the reference Warshall
# ----------------------------------------------------------------------

test_that("randomly permuted DAGs match the Warshall truth and expose the 0.2.0 motor", {
  set.seed(4071)
  n_motor_wrong <- 0L
  for (rep in 1:25) {
    n <- sample(4:40, 1)
    # Random DAG in index order, then a random relabeling of vertices
    adj0 <- lapply(seq_len(n), function(v) {
      if (v == n) return(integer(0))
      cand <- seq.int(v + 1L, n)
      cand[stats::runif(length(cand)) < 0.3]
    })
    perm <- sample(n)             # perm[old] = new label
    adj <- vector("list", n)
    for (v in seq_len(n)) adj[[perm[v]]] <- sort(perm[adj0[[v]]])

    truth <- canon(ref_alexandrov_base(adj, n))
    new <- generate_alexandrov_topology(adj, n)
    expect_identical(canon(new$base), truth,
                     info = sprintf("permuted DAG rep %d (n=%d)", rep, n))
    expect_true(new$input_acyclic)
    expect_identical(new$collapsed_classes, list())

    # The raw motor (the 0.2.0 behavior, still the inner engine) must be
    # wrong on at least a good share of these inputs -- that is the
    # defect C-40 repaired. Not on every draw: some permutations are
    # close to order-preserving.
    raw <- alexandrov_topology_engine(adj, n)
    if (!identical(canon(raw$base), truth)) n_motor_wrong <- n_motor_wrong + 1L
  }
  expect_gte(n_motor_wrong, 10L)
})

# ----------------------------------------------------------------------
# Battery (iii): cyclic digraphs against the hand condensation
# ----------------------------------------------------------------------

test_that("cyclic digraphs match the Warshall truth and report their collapsed classes", {
  set.seed(4072)
  n_with_cycles <- 0L
  for (rep in 1:25) {
    n <- sample(3:24, 1)
    p <- stats::runif(1, 0.05, 0.5)
    adj <- lapply(seq_len(n), function(v) {
      cand <- setdiff(seq_len(n), v)
      sort(cand[stats::runif(length(cand)) < p])
    })
    R <- ref_reach_matrix(adj, n)
    truth <- canon(unique(lapply(seq_len(n), function(v) which(R[v, ]))))

    new <- generate_alexandrov_topology(adj, n)
    expect_identical(canon(new$base), truth,
                     info = sprintf("cyclic rep %d (n=%d)", rep, n))

    # Hand condensation: classes of mutual reachability
    mutual <- R & t(R)
    classes <- unique(lapply(seq_len(n), function(v) which(mutual[v, ])))
    nontrivial <- canon(Filter(function(s) length(s) > 1L, classes))
    expect_identical(canon(new$collapsed_classes), nontrivial,
                     info = sprintf("collapsed classes rep %d", rep))
    expect_identical(new$input_acyclic, length(nontrivial) == 0L)
    if (length(nontrivial)) n_with_cycles <- n_with_cycles + 1L

    # Components must agree with the comparability components computed
    # by hand from the reachability matrix: x ~ y iff comparable
    comparable <- R | t(R)
    comp_id <- integer(n); cur <- 0L
    for (s in seq_len(n)) {
      if (comp_id[s] != 0L) next
      cur <- cur + 1L
      frontier <- s; comp_id[s] <- cur
      while (length(frontier)) {
        nxt <- which(apply(comparable[frontier, , drop = FALSE], 2, any) &
                       comp_id == 0L)
        comp_id[nxt] <- cur
        frontier <- nxt
      }
    }
    hand_comps <- canon(unname(split(seq_len(n), comp_id)))
    expect_identical(canon(new$components), hand_comps,
                     info = sprintf("components rep %d", rep))
  }
  expect_gte(n_with_cycles, 10L)
})

# ----------------------------------------------------------------------
# The named cases
# ----------------------------------------------------------------------

test_that("the 3-cycle collapses to a point-like topology", {
  # 1->2->3->1: everything reaches everything, one upset {1,2,3}
  out <- generate_alexandrov_topology(list(2L, 3L, 1L), 3L)
  expect_identical(canon(out$base), list(c(1L, 2L, 3L)))
  expect_true(isTRUE(out$connected))
  expect_identical(canon(out$components), list(c(1L, 2L, 3L)))
  expect_false(out$input_acyclic)
  expect_identical(out$collapsed_classes, list(c(1L, 2L, 3L)))
})

test_that("the reversed chain 3->2->1 is repaired", {
  # Edges 3->2, 2->1: truth reach(3)={1,2,3}, reach(2)={1,2}, reach(1)={1}
  adj <- list(integer(0), 1L, 2L)
  out <- generate_alexandrov_topology(adj, 3L)
  expect_identical(canon(out$base), list(1L, c(1L, 2L), c(1L, 2L, 3L)))
  expect_true(out$input_acyclic)
  expect_false(out$input_index_ordered)
  expect_identical(out$collapsed_classes, list())
  # And the raw 0.2.0 motor gets exactly this case wrong
  raw <- alexandrov_topology_engine(adj, 3L)
  expect_false(identical(canon(raw$base), canon(out$base)))
})

test_that("expect = 'index_ordered_dag' verifies the strict contract", {
  # Passes on a visibility graph
  g <- horizontal_visibility_graph(c(3, 1, 4, 1, 5), directed = TRUE)
  out <- generate_alexandrov_topology(g$out_adjacency, g$n,
                                      expect = "index_ordered_dag")
  expect_true(out$input_index_ordered)
  # Stops on the reversed chain, naming the offending edge
  expect_error(
    generate_alexandrov_topology(list(integer(0), 1L, 2L), 3L,
                                 expect = "index_ordered_dag"),
    "2 -> 1"
  )
  # Stops on a cycle
  expect_error(
    generate_alexandrov_topology(list(2L, 3L, 1L), 3L,
                                 expect = "index_ordered_dag"),
    "index_ordered_dag"
  )
})

test_that("enumeration transfers through the condensation bijectively", {
  # Cyclic input, small enough to enumerate: open sets of the input are
  # in bijection with open sets of the condensation
  adj <- list(2L, c(1L, 3L), 4L, integer(0), c(4L, 1L))
  # SCC {1,2}; 5 -> {4, 1}; 3 -> 4
  out <- generate_alexandrov_topology(adj, 5L, max_open_sets = 1000L,
                                      verify_axioms = TRUE)
  expect_true(out$complete)
  expect_true(out$axioms_ok)
  # Every enumerated open set must be an upset of the reference closure
  R <- ref_reach_matrix(adj, 5L)
  for (U in out$topology) {
    if (length(U) == 0L || length(U) == 5L) next
    reached <- unique(unlist(lapply(U, function(v) which(R[v, ]))))
    expect_true(all(reached %in% U),
                info = paste("not an upset:", paste(U, collapse = ",")))
  }
  # The union closure of the base, computed by hand, has the same size
  base_sets <- canon(out$base)
  closure <- new.env(hash = TRUE, parent = emptyenv())
  assign("0", integer(0), envir = closure)
  assign(paste(1:5, collapse = ","), 1:5, envir = closure)
  frontier <- base_sets
  for (s in base_sets) assign(paste(s, collapse = ","), s, envir = closure)
  repeat {
    added <- list()
    keys <- ls(closure)
    current <- mget(keys, envir = closure)
    for (f in frontier) for (t in current) {
      u <- sort(unique(c(f, t)))
      k <- if (length(u)) paste(u, collapse = ",") else "0"
      if (!exists(k, envir = closure)) {
        assign(k, u, envir = closure); added <- c(added, list(u))
      }
    }
    if (!length(added)) break
    frontier <- added
  }
  expect_identical(out$n_open_sets, length(ls(closure)))
})

# ----------------------------------------------------------------------
# C-43: the intents-extents theorem as a property test
# ----------------------------------------------------------------------

test_that("forward and backward base sizes are equal for arbitrary digraphs (C-43)", {
  set.seed(4073)
  for (rep in 1:40) {
    n <- sample(2:9, 1)
    p <- stats::runif(1, 0.05, 0.9)
    out_adj <- lapply(seq_len(n), function(v) {
      cand <- setdiff(seq_len(n), v)
      sort(cand[stats::runif(length(cand)) < p])
    })
    in_adj <- lapply(seq_len(n), function(v) {
      which(vapply(seq_len(n), function(w) v %in% out_adj[[w]], logical(1)))
    })
    tf <- generate_topology(out_adj, n, max_open_sets = 0L)
    tb <- generate_topology(in_adj, n, max_open_sets = 0L)
    if (isTRUE(tf$base_complete) && isTRUE(tb$base_complete)) {
      expect_identical(length(tf$base), length(tb$base),
                       info = sprintf("rep %d (n=%d): |B+| != |B-|", rep, n))
    }
    inv <- bitopology_invariants(tf, tb, n)
    expect_null(inv$irreversibility_base)
    expect_identical(inv$forward_base_size, length(tf$base))
    expect_identical(inv$backward_base_size, length(tb$base))
  }
})

# ----------------------------------------------------------------------
# A-1: the Alexandrov branch is the chain on visibility graphs
# ----------------------------------------------------------------------

test_that("the Alexandrov topology of any visibility graph is the chain (A-1)", {
  set.seed(4074)
  for (rep in 1:10) {
    n <- sample(5:60, 1)
    s <- cumsum(rnorm(n))
    for (gt in c("hvg", "nvg")) {
      g <- if (gt == "hvg") horizontal_visibility_graph(s, directed = TRUE)
           else natural_visibility_graph(s, directed = TRUE)
      alex <- generate_alexandrov_topology(g$out_adjacency, g$n)
      chain <- lapply(seq_len(n), function(i) seq.int(i, n))
      expect_identical(canon(alex$base), canon(chain),
                       info = sprintf("%s rep %d (n=%d)", gt, rep, n))
      expect_identical(length(alex$components), 1L)
      expect_true(isTRUE(alex$connected))
    }
  }
})
