# ----------------------------------------------------------------------
# Internal helpers for the generalized Alexandrov construction (C-40)
# ----------------------------------------------------------------------

# Neighbors the C++ engine would use: valid 1-based indices only.
# The engine silently ignores out-of-range entries; the R-side analysis
# must see exactly the digraph the engine sees.
alexandrov_valid_neighbors <- function(out_adjacency, n_elements) {
  lapply(out_adjacency, function(nb) {
    nb <- as.integer(nb)
    nb[!is.na(nb) & nb >= 1L & nb <= n_elements]
  })
}

# Does every edge go from a lower to a higher index? That is the contract
# the reverse-order propagation of the engine actually relies on -- it is
# strictly stronger than acyclicity.
alexandrov_index_ordered <- function(adj) {
  for (v in seq_along(adj)) {
    if (any(adj[[v]] <= v)) return(FALSE)
  }
  TRUE
}

# Smallest open set of each point of the topology generated by a subbase on
# 1..n: the intersection of the members that contain the point, or the whole
# set when no member does.
minimal_open_sets <- function(subbase, n) {
  holders <- vector("list", n)
  for (j in seq_along(subbase)) {
    for (x in subbase[[j]]) holders[[x]] <- c(holders[[x]], j)
  }
  lapply(seq_len(n), function(x) {
    if (is.null(holders[[x]])) return(seq_len(n))
    sort(as.integer(Reduce(intersect, subbase[holders[[x]]])))
  })
}

# Pairwise connectedness of (V, tau+, tau-), decided from the two subbases by
# the strong connectivity of the digraph H with an arc x -> y when y is in the
# smallest tau+-open set of x or x is in the smallest tau--open set of y (see
# ?bitopology_invariants). A strongly connected component that no arc leaves,
# the first that Tarjan's algorithm completes, is a witness.
pairwise_connectedness <- function(forward_subbase, backward_subbase, n) {
  out <- list(pairwise_connected = TRUE, clopen_forward = NULL,
              clopen_backward = NULL)
  if (n < 2L) return(out)
  up <- minimal_open_sets(forward_subbase, n)
  um <- minimal_open_sets(backward_subbase, n)
  adj <- up
  for (y in seq_len(n)) {
    for (x in um[[y]]) adj[[x]] <- c(adj[[x]], y)
  }
  adj <- lapply(seq_len(n), function(x) {
    a <- unique(as.integer(adj[[x]]))
    a[a != x]
  })
  scc <- alexandrov_tarjan_scc(adj, n)
  if (scc$n_comp == 1L) return(out)
  sink <- which(scc$comp_of == 1L)
  out$pairwise_connected <- FALSE
  out$clopen_forward <- sink
  out$clopen_backward <- setdiff(seq_len(n), sink)
  out
}

# Iterative Tarjan: strongly connected components of the digraph.
# Returns comp_of (1-based membership, components emitted sinks-first,
# i.e. in reverse topological order of the condensation) and n_comp.
alexandrov_tarjan_scc <- function(adj, n) {
  index_of <- integer(n)      # 0 = unvisited
  lowlink <- integer(n)
  on_stack <- logical(n)
  scc_stack <- integer(0)
  comp_of <- integer(n)
  n_comp <- 0L
  counter <- 0L

  for (root in seq_len(n)) {
    if (index_of[root] != 0L) next
    # Explicit DFS stack: each frame is (vertex, next-neighbor position)
    stack_v <- integer(0)
    stack_i <- integer(0)
    stack_v <- c(stack_v, root)
    stack_i <- c(stack_i, 1L)
    counter <- counter + 1L
    index_of[root] <- counter
    lowlink[root] <- counter
    scc_stack <- c(scc_stack, root)
    on_stack[root] <- TRUE

    while (length(stack_v) > 0L) {
      top <- length(stack_v)
      v <- stack_v[top]
      i <- stack_i[top]
      nb <- adj[[v]]
      if (i <= length(nb)) {
        stack_i[top] <- i + 1L
        w <- nb[i]
        if (index_of[w] == 0L) {
          counter <- counter + 1L
          index_of[w] <- counter
          lowlink[w] <- counter
          scc_stack <- c(scc_stack, w)
          on_stack[w] <- TRUE
          stack_v <- c(stack_v, w)
          stack_i <- c(stack_i, 1L)
        } else if (on_stack[w]) {
          lowlink[v] <- min(lowlink[v], index_of[w])
        }
      } else {
        # Post-order: fold lowlink into the parent, pop SCC if root
        stack_v <- stack_v[-top]
        stack_i <- stack_i[-top]
        if (length(stack_v) > 0L) {
          p <- stack_v[length(stack_v)]
          lowlink[p] <- min(lowlink[p], lowlink[v])
        }
        if (lowlink[v] == index_of[v]) {
          n_comp <- n_comp + 1L
          repeat {
            w <- scc_stack[length(scc_stack)]
            scc_stack <- scc_stack[-length(scc_stack)]
            on_stack[w] <- FALSE
            comp_of[w] <- n_comp
            if (w == v) break
          }
        }
      }
    }
  }
  list(comp_of = comp_of, n_comp = n_comp)
}

#' Alexandrov topology of the reachability preorder of a digraph
#'
#' @description
#' Computes the Alexandrov topology of the reachability preorder of a directed
#' graph: its open sets are the sets closed under following arcs, and the
#' smallest open set containing \eqn{v} is the set of vertices reachable from
#' \eqn{v} by directed paths, \eqn{v} included. It accepts any digraph and
#' reports which of three cases it received; [generate_bitopology()] applies
#' it to directed visibility graphs, where it is always the same chain.
#'
#' @param out_adjacency List of length \code{n_elements}; element \code{i} is an
#'   integer vector with the 1-based indices of the direct successors of vertex
#'   \code{i}. Indices outside \eqn{1, \ldots, n} are ignored. No default.
#' @param n_elements Integer scalar, at least 1: the number of vertices. Must
#'   equal \code{length(out_adjacency)}. No default.
#' @param max_open_sets Non-negative integer scalar (default 0, no
#'   enumeration): the enumeration of the open sets stops as soon as their
#'   number exceeds it. There can be up to \eqn{2^n} of them.
#' @param check_connected Logical scalar (default \code{TRUE}): whether to
#'   compute the connected components.
#' @param verify_axioms Logical scalar (default \code{FALSE}): whether to check,
#'   when the enumeration is complete, that the enumerated family contains the
#'   empty set and the whole set and is closed under the union and the
#'   intersection of any two members, the axioms of a topology on a finite
#'   set.
#' @param expect Character scalar: \code{"any"} (default) accepts every
#'   digraph; \code{"index_ordered_dag"} verifies, in \eqn{O(m)}, that every arc
#'   goes from a lower to a higher index, as in a directed visibility graph, and
#'   stops with an error naming the first arc that does not.
#' @return A \code{list} with the elements of [generate_topology()] and three
#'   more:
#'   \describe{
#'     \item{subbase, base}{The same list of integer vectors: the distinct sets
#'       of reachable vertices, which form the minimal base of the topology.
#'       They are not closed under intersection in general (see Methodological
#'       notes).}
#'     \item{base_complete}{Always \code{TRUE}: the minimal base is computed
#'       exactly.}
#'     \item{connected, components}{Connectedness and the connected components,
#'       as in [generate_topology()].}
#'     \item{topology, n_open_sets, topology_complete}{The enumerated open sets
#'       and their flags, as in [generate_topology()].}
#'     \item{input_index_ordered}{Logical: whether every arc went from a lower
#'       to a higher index.}
#'     \item{input_acyclic}{Logical: whether the digraph had no directed
#'       cycle.}
#'     \item{collapsed_classes}{List of integer vectors: the strongly connected
#'       components with more than one vertex, whose vertices the topology
#'       cannot tell apart; \code{list()} when there are none.}
#'   }
#'
#' @details
#' Three cases are handled. (1) Every arc goes from a lower to a higher index,
#' as in directed visibility graphs: the reachable sets are propagated in
#' reverse index order as bitsets, \eqn{\mathrm{reach}(v) = \{v\} \cup
#' \bigcup_{w \in \mathrm{out}(v)} \mathrm{reach}(w)}, in
#' \eqn{O(n m / 64)} word operations. (2) An acyclic digraph in another order:
#' the vertices are first re-indexed along a topological order. (3) A digraph
#' with directed cycles: mutually reachable vertices have the same reachable
#' set, so the topology is computed on the condensation, found with the
#' algorithm of Tarjan (1972), and expanded back; the expansion is a bijection
#' between the open sets of the condensation and those of the input, so every
#' reported field carries over exactly. A set is closed under following arcs
#' if and only if it is closed under following directed paths, which is why
#' propagating along single arcs gives the reachable sets.
#'
#' @section Methodological notes:
#' \emph{The base is minimal, not intersection-closed.} For the arcs
#' \eqn{a \to c}, \eqn{a \to d}, \eqn{b \to c}, \eqn{b \to d}, the reachable
#' sets are \eqn{\{a, c, d\}}, \eqn{\{b, c, d\}}, \eqn{\{c\}} and \eqn{\{d\}};
#' the first two meet in \eqn{\{c, d\}}, which is open, as the union of
#' \eqn{\{c\}} and \eqn{\{d\}}, but is not one of them. The number of base sets
#' is the number of strongly connected components.
#'
#' \emph{Relation with the forward topology.} For every digraph, the
#' Alexandrov topology is contained in the forward topology generated by the
#' closed forward neighbourhoods \eqn{N^+[v]} (see [generate_bitopology()]):
#' each reachable set is the union of the \eqn{N^+[w]} of its points. It is not
#' contained in the undirected topology in general: on the path
#' \eqn{1 \to 2 \to 3 \to 4}, \eqn{\{4\}} is open here and not in the
#' undirected topology, whose smallest open set containing 4 is
#' \eqn{\{3, 4\}}.
#'
#' The connection between finite topologies and preorders goes back to
#' Alexandroff (1937), after whom these spaces are named.
#'
#' @section Dependencies:
#' The compiled engine (C++ through 'Rcpp') for the propagation and the
#' components; base R for the condensation.
#'
#' @references
#'   Alexandroff, P. (1937). Diskrete Räume. Recueil Mathématique (Matematicheskii
#'   Sbornik), Nouvelle Série, 2(44)(3), 501-519. https://www.mathnet.ru/eng/sm5579
#'
#'   Tarjan, R. (1972). Depth-first search and linear graph algorithms. SIAM
#'   Journal on Computing, 1(2), 146-160. https://doi.org/10.1137/0201010
#'
#' @seealso [generate_topology()] for the topologies of closed
#'   neighbourhoods, [generate_bitopology()] for the time-series pipeline.
#'
#' @examples
#' g <- horizontal_visibility_graph(c(3, 1, 4, 1, 5), directed = TRUE)
#' alex <- generate_alexandrov_topology(g$out_adjacency, g$n)
#' alex$base
#' alex$connected
#'
#' cross <- generate_alexandrov_topology(list(c(3L, 4L), c(3L, 4L), integer(0), integer(0)), 4L)
#' cross$base
#'
#' cyc <- generate_alexandrov_topology(list(2L, 3L, 1L), 3L)
#' cyc$collapsed_classes
#' @export
generate_alexandrov_topology <- function(out_adjacency, n_elements,
                                         max_open_sets = 0L,
                                         check_connected = TRUE,
                                         verify_axioms = FALSE,
                                         expect = c("any", "index_ordered_dag")) {
  expect <- match.arg(expect)
  if (!is.list(out_adjacency)) {
    stop("'out_adjacency' must be a list of integer vectors.", call. = FALSE)
  }
  n_elements <- check_count(n_elements, "n_elements", 1L)
  if (length(out_adjacency) != n_elements) {
    stop("Length of 'out_adjacency' must equal 'n_elements'.", call. = FALSE)
  }
  max_open_sets <- check_count(max_open_sets, "max_open_sets", 0L)
  enumerate <- max_open_sets > 0L

  adj <- alexandrov_valid_neighbors(out_adjacency, n_elements)
  index_ordered <- alexandrov_index_ordered(adj)

  if (expect == "index_ordered_dag" && !index_ordered) {
    offender <- NULL
    for (v in seq_along(adj)) {
      bad <- adj[[v]][adj[[v]] <= v]
      if (length(bad)) { offender <- c(v, bad[1L]); break }
    }
    stop("'expect = \"index_ordered_dag\"' but the input has the edge ",
         offender[1L], " -> ", offender[2L],
         ", which does not go from a lower to a higher index. ",
         "The strict visibility-graph contract does not hold; pass ",
         "'expect = \"any\"' if generalization to the reachability ",
         "preorder is intended.", call. = FALSE)
  }

  if (index_ordered) {
    # Regime 1: the original engine, unchanged and bit-identical.
    result <- alexandrov_topology_engine(
      out_adjacency = out_adjacency,
      n_elements = n_elements,
      max_open_sets = max_open_sets,
      enumerate_topology = enumerate,
      check_connected = check_connected,
      verify_axioms = verify_axioms
    )
    result$input_index_ordered <- TRUE
    result$input_acyclic <- TRUE
    result$collapsed_classes <- list()
    return(result)
  }

  # Regimes 2 and 3: condense, re-index topologically, run the same
  # engine on the condensation, expand back to the vertices.
  scc <- alexandrov_tarjan_scc(adj, n_elements)
  n_comp <- scc$n_comp
  # Tarjan emits components sinks-first (reverse topological order), so
  # reversing the emission index yields a topological order in which
  # every condensation edge goes from a lower to a higher class index.
  topo_id <- n_comp + 1L - scc$comp_of

  members <- vector("list", n_comp)
  for (v in seq_len(n_elements)) {
    cid <- topo_id[v]
    members[[cid]] <- c(members[[cid]], v)
  }
  members <- lapply(members, sort)

  cond_adj <- vector("list", n_comp)
  for (v in seq_len(n_elements)) {
    cv <- topo_id[v]
    cw <- topo_id[adj[[v]]]
    cw <- cw[cw != cv]
    if (length(cw)) {
      cond_adj[[cv]] <- c(cond_adj[[cv]], cw)
    }
  }
  cond_adj <- lapply(cond_adj, function(x) {
    if (is.null(x)) integer(0) else sort(unique(as.integer(x)))
  })

  cond <- alexandrov_topology_engine(
    out_adjacency = cond_adj,
    n_elements = n_comp,
    max_open_sets = max_open_sets,
    enumerate_topology = enumerate,
    check_connected = check_connected,
    verify_axioms = verify_axioms
  )

  # Expansion: a set of classes becomes the sorted set of their vertices.
  # It is a bijection between the condensation's open sets and the
  # input's open sets, so counts and flags transfer unchanged.
  expand <- function(class_set) {
    if (length(class_set) == 0L) return(integer(0))
    sort(unlist(members[class_set], use.names = FALSE))
  }

  result <- cond
  result$subbase <- lapply(cond$subbase, expand)
  result$base <- lapply(cond$base, expand)
  result$components <- lapply(cond$components, expand)
  if (!is.null(cond$topology)) {
    result$topology <- lapply(cond$topology, expand)
  }

  collapsed <- members[lengths(members) > 1L]
  if (length(collapsed)) {
    collapsed <- collapsed[order(vapply(collapsed, min, integer(1)))]
  }
  result$input_index_ordered <- FALSE
  result$input_acyclic <- (n_comp == n_elements)
  result$collapsed_classes <- collapsed
  result
}


#' Bitopological analysis of a time series
#'
#' @description
#' Builds the directed visibility graph of a series (horizontal or natural, at
#' equally or unequally spaced instants) and from it four topologies on the
#' observations: the undirected topology \eqn{\tau} of the closed
#' neighbourhoods, the forward topology \eqn{\tau^+} of the closed forward
#' neighbourhoods \eqn{N^+[v] = \{v\} \cup \{w : v \to w\}}, the backward
#' topology \eqn{\tau^-} of the closed backward neighbourhoods
#' \eqn{N^-[v] = \{v\} \cup \{w : w \to v\}}, and optionally the Alexandrov
#' topology of reachability; then computes their invariants with
#' [bitopology_invariants()]. The triple \eqn{(V, \tau^+, \tau^-)} is a
#' bitopological space in the sense of Kelly (1963).
#'
#' @param series Numeric vector with at least two observations and no
#'   \code{NA}, \code{NaN} or infinite values. No default.
#' @param graph_type Character scalar: \code{"hvg"} (default) for the
#'   horizontal visibility graph or \code{"nvg"} for the natural one.
#' @param max_open_sets Non-negative integer scalar (default 0, no
#'   enumeration), passed to [generate_topology()] and
#'   [generate_alexandrov_topology()]. The pairwise-connectedness check of
#'   [bitopology_invariants()] does not need the enumeration.
#' @param max_base_sets Positive integer scalar (default 100,000), passed to
#'   [generate_topology()].
#' @param alexandrov Logical scalar (default \code{TRUE}): whether to compute
#'   the Alexandrov topology too.
#' @param times \code{NULL} (default) for the instants \eqn{1, \ldots, n}, or
#'   a numeric, \code{Date} or date-time vector of finite, strictly increasing
#'   instants of the same length as \code{series}. It matters only for the
#'   natural graph.
#' @return A \code{list} with \code{graph} (the directed visibility graph, as
#'   returned by [horizontal_visibility_graph()] or [natural_visibility_graph()]
#'   with \code{directed = TRUE}), \code{undirected}, \code{forward} and
#'   \code{backward} (results of [generate_topology()]), \code{alexandrov} (the
#'   result of [generate_alexandrov_topology()], or \code{NULL}) and
#'   \code{invariants} (the result of [bitopology_invariants()]).
#'
#' @details
#' Every arc of a directed visibility graph goes from the earlier to the later
#' observation, so the out-neighbour lists give \eqn{\tau^+} and the
#' in-neighbour lists \eqn{\tau^-}; the same engine computes the three
#' topologies of closed neighbourhoods. Consecutive observations always see
#' each other, so the digraph contains the path \eqn{1 \to 2 \to \cdots \to n},
#' reachability is the total order, and the Alexandrov topology is the same
#' chain of sets \eqn{\{i, \ldots, n\}} for every series; it describes the
#' class of visibility graphs and not the series, and \code{alexandrov = FALSE}
#' skips it. Because every arc goes forward in time, two more comparisons are
#' constant on the class: \eqn{\{n\}} is open in \eqn{\tau^+} (the last
#' observation has no later neighbour) and not in \eqn{\tau^-} (the only member
#' of the backward subbase that contains \eqn{n} is its closed
#' in-neighbourhood, which also contains \eqn{n - 1}, since consecutive
#' observations see each other), so the two topologies differ for
#' every series with \eqn{n \ge 2}, a reversible one included; and the
#' bitopological space is pairwise disconnected for every such series (see
#' [bitopology_invariants()]). What T1 relates is \eqn{\tau^+} of a series to
#' \eqn{\tau^-} of its reversal, not \eqn{\tau^+} to \eqn{\tau^-} of the same
#' series.
#'
#' \strong{Theorem T1 (time reversal).} Let a series \eqn{x} be observed at
#' strictly increasing instants \eqn{t}, write \eqn{\tilde{x}_i = x_{n+1-i}},
#' \eqn{\tilde{t}_i = -t_{n+1-i}} (what [time_reverse()] returns) and
#' \eqn{r(i) = n + 1 - i}. Under either visibility criterion, \eqn{\{i, j\}} is
#' an edge for \eqn{(\tilde{x}, \tilde{t})} if and only if
#' \eqn{\{r(i), r(j)\}} is an edge for \eqn{(x, t)}; \eqn{r} carries the closed
#' forward neighbourhood of \eqn{i} for \eqn{(\tilde{x}, \tilde{t})} onto the
#' closed backward neighbourhood of \eqn{r(i)} for \eqn{(x, t)}, and the
#' backward one onto the forward one; hence \eqn{r} is a homeomorphism from
#' \eqn{\tau^+(\tilde{x}, \tilde{t})} onto \eqn{\tau^-(x, t)} and from
#' \eqn{\tau^-(\tilde{x}, \tilde{t})} onto \eqn{\tau^+(x, t)}. Consequently
#' \eqn{C^+(\tilde{x}, \tilde{t}) = C^-(x, t)} and
#' \eqn{C^-(\tilde{x}, \tilde{t}) = C^+(x, t)}, the two base sizes are
#' exchanged, \code{asymmetry_direction}, \eqn{D = C^- - C^+}, changes sign,
#' and \code{irreversibility_components},
#' \eqn{I_C = |C^+ - C^-| / \max(C^+, C^-)}, is unchanged.
#'
#' \emph{Proof.} The horizontal criterion for \eqn{i < j} involves only the
#' values strictly between them, which \eqn{r} carries onto those strictly
#' between \eqn{r(j)} and \eqn{r(i)}, with the same values. For the natural
#' criterion, the quantity \eqn{D(a, b, k) = x_a (t_b - t_k) + x_b (t_k - t_a) -
#' x_k (t_b - t_a)} of [natural_visibility_graph()] computed for
#' \eqn{(\tilde{x}, \tilde{t})} at \eqn{(r(b), r(a), r(k))} equals \eqn{D(a, b,
#' k)} for \eqn{(x, t)}, term by term, so each condition transfers to the
#' reflected pair. Arcs run from the lower index to the higher one and \eqn{r}
#' inverts that order, so forward closed neighbourhoods become backward ones;
#' a bijection between the subbases of two topologies that commutes with the
#' point map is a homeomorphism of the topologies they generate, and it carries
#' bases and connected components onto each other. \eqn{\square}
#'
#' @section Methodological notes:
#' \emph{What T1 says and what it does not.} T1 fixes the meaning of the sign
#' of \code{asymmetry_direction}: reading the series backwards, with its
#' instants reflected, changes it. When the series and the gaps between its
#' instants both read the same in the two directions (a palindrome on a
#' palindromic grid; with \code{times = NULL}, a palindrome), the reversed
#' series is the same series up to a translation of time and the asymmetry is
#' exactly zero. T1 has no converse: a non-zero asymmetry does not show that
#' the process that generated the series is irreversible, and a zero asymmetry
#' does not show that it is reversible. The probabilistic statement it
#' supports is about laws: if the joint law of the observations together with
#' their instants is invariant under the joint reversal (values read
#' backwards, instants reflected), the law of \code{asymmetry_direction} is
#' symmetric about zero, the mass at zero included; with
#' \code{times = NULL}, or with fixed instants whose gaps read the same in
#' both directions, the condition is that the law of the values equals the law
#' of their reversal, and so it is for the horizontal criterion with any fixed
#' instants, which it does not use. For the natural criterion with fixed
#' instants whose gaps are not palindromic, reversing the values alone is
#' another operation, to which this statement does not apply.
#' None of this says anything about stationarity or about the generating
#' process. For a statistical treatment of time
#' irreversibility with visibility graphs, see Lacasa et al. (2012), who
#' estimate it by the Kullback-Leibler divergence between the in- and
#' out-degree distributions of the directed horizontal visibility graph.
#'
#' \emph{Instants.} Reversing the values over the same instants is a different
#' operation as soon as the gaps between consecutive instants are not
#' palindromic. The horizontal criterion does not use the instants, so for it
#' the two operations give the same graphs and T1 holds for both; for the
#' natural criterion T1 can fail for the reversal of the values alone: with
#' the values 0, 1, 2 at the instants 0, 1, 3, it creates the edge
#' \eqn{\{1, 3\}}, which neither the original series nor its reversal with
#' reflected instants has; see [time_reverse()]. With the natural criterion the theorem holds exactly in
#' the computation as well, under the hypotheses of
#' [natural_visibility_exactness], because the criterion is then decided
#' exactly and negating the instants is exact.
#'
#' @section Dependencies:
#' [horizontal_visibility_graph()] or [natural_visibility_graph()],
#' [generate_topology()], [generate_alexandrov_topology()] and
#' [bitopology_invariants()]; the compiled engine through 'Rcpp'.
#'
#' @references
#'   Kelly, J. C. (1963). Bitopological spaces. Proceedings of the London
#'   Mathematical Society, s3-13(1), 71-89. https://doi.org/10.1112/plms/s3-13.1.71
#'
#'   Lacasa, L., Nuñez, A., Roldán, É., Parrondo, J. M. R., & Luque, B. (2012).
#'   Time series irreversibility: A visibility graph approach. The European
#'   Physical Journal B, 85(6), Article 217.
#'   https://doi.org/10.1140/epjb/e2012-20809-8
#'
#' @seealso [bitopology_invariants()], [time_reverse()],
#'   [generate_topology()], [generate_alexandrov_topology()].
#'
#' @examples
#' series <- c(3, 1, 4, 1, 5, 9, 2, 6)
#' bt <- generate_bitopology(series, graph_type = "hvg")
#' bt$invariants$forward_components
#' bt$invariants$backward_components
#' bt$invariants$asymmetry_direction
#'
#' rv <- time_reverse(series)
#' generate_bitopology(rv$series, graph_type = "hvg")$invariants$asymmetry_direction
#'
#' t <- c(0, 1, 3, 4, 7, 8, 9, 12)
#' bn <- generate_bitopology(series, graph_type = "nvg", times = t)
#' rn <- time_reverse(series, t)
#' bn$invariants$asymmetry_direction
#' generate_bitopology(rn$series, graph_type = "nvg", times = rn$times)$invariants$asymmetry_direction
#' @export
generate_bitopology <- function(series,
                                graph_type = c("hvg", "nvg"),
                                max_open_sets = 0L,
                                max_base_sets = 100000L,
                                alexandrov = TRUE,
                                times = NULL) {
  graph_type <- match.arg(graph_type)
  validate_series(series)
  if (length(series) < 2L) {
    stop("'series' must have at least 2 observations.", call. = FALSE)
  }

  g <- if (graph_type == "hvg") {
    horizontal_visibility_graph(series, directed = TRUE, times = times)
  } else {
    natural_visibility_graph(series, directed = TRUE, times = times)
  }
  n <- g$n

  tau_undirected <- generate_topology(g$adjacency, n,
                                      max_open_sets = max_open_sets,
                                      max_base_sets = max_base_sets)
  tau_forward <- generate_topology(g$out_adjacency, n,
                                   max_open_sets = max_open_sets,
                                   max_base_sets = max_base_sets)
  tau_backward <- generate_topology(g$in_adjacency, n,
                                    max_open_sets = max_open_sets,
                                    max_base_sets = max_base_sets)
  tau_alexandrov <- NULL
  if (alexandrov) {
    tau_alexandrov <- generate_alexandrov_topology(g$out_adjacency, n,
                                                   max_open_sets = max_open_sets)
  }

  list(
    graph = g,
    undirected = tau_undirected,
    forward = tau_forward,
    backward = tau_backward,
    alexandrov = tau_alexandrov,
    invariants = bitopology_invariants(tau_forward, tau_backward, n,
                                       tau_undirected, tau_alexandrov)
  )
}


#' Invariants of a pair of forward and backward topologies
#'
#' @description
#' Given the forward topology \eqn{\tau^+} and the backward topology
#' \eqn{\tau^-} computed by [generate_topology()], reports their numbers of
#' connected components and of base sets, two summaries of the difference
#' between the component counts, the pairwise connectedness of the
#' bitopological space, decided exactly, and, when supplied, comparisons with the
#' Alexandrov and the undirected topologies.
#'
#' @param forward Result of [generate_topology()] for the out-neighbour lists,
#'   computed with \code{check_connected = TRUE}. No default.
#' @param backward Result of [generate_topology()] for the in-neighbour lists,
#'   computed with \code{check_connected = TRUE}. No default.
#' @param n_elements Integer scalar: the number of points; must equal the
#'   number of points covered by the components. No default.
#' @param undirected Optional result of [generate_topology()] for the
#'   undirected lists. Default \code{NULL}.
#' @param alexandrov Optional result of [generate_alexandrov_topology()] for
#'   the out-neighbour lists. Default \code{NULL}.
#' @return A \code{list} with:
#'   \describe{
#'     \item{forward_components, backward_components}{Integers \eqn{C^+} and
#'       \eqn{C^-}: the numbers of connected components, exact even when a base
#'       was truncated.}
#'     \item{forward_connected, backward_connected}{Logical.}
#'     \item{forward_base_size, backward_base_size}{Integers \eqn{|B^+|} and
#'       \eqn{|B^-|}: the numbers of sets in the two bases, or \code{NA} when
#'       the corresponding base was truncated.}
#'     \item{forward_base_complete, backward_base_complete}{Logical: the
#'       \code{base_complete} flags of the two topologies.}
#'     \item{irreversibility_components}{Numeric in \eqn{[0, 1]}:
#'       \eqn{I_C = |C^+ - C^-| / \max(C^+, C^-)}.}
#'     \item{asymmetry_direction}{Integer \eqn{D = C^- - C^+}.}
#'     \item{pairwise}{List with \code{pairwise_connected} (logical, never
#'       \code{NA}: the property is decided exactly, without enumerating either
#'       topology) and, when it is \code{FALSE}, \code{clopen_forward}, a proper
#'       non-empty \eqn{\tau^+}-open set whose complement is \eqn{\tau^-}-open,
#'       and \code{clopen_backward}, that complement.}
#'     \item{resolution}{\code{NULL} unless \code{alexandrov} is given;
#'       otherwise a list with \code{alexandrov_base_size},
#'       \code{alexandrov_components}, \code{alexandrov_connected},
#'       \code{nada_forward_base_gain} and \code{nada_backward_base_gain}
#'       (\eqn{|B^+| - |B_A|} and \eqn{|B^-| - |B_A|}, \code{NA} with a
#'       truncated base) and the same differences divided by
#'       \eqn{\max(|B_A|, 1)} (\code{nada_forward_relative_gain},
#'       \code{nada_backward_relative_gain}).}
#'     \item{undirected_info}{\code{NULL} unless \code{undirected} is given;
#'       otherwise a list with \code{undirected_components},
#'       \code{undirected_connected} and \code{undirected_base_size}
#'       (\code{NA} with a truncated base).}
#'   }
#'
#' @details
#' \strong{The two base sizes are equal.} Let \eqn{R} be a binary relation on
#' a finite non-empty set \eqn{V}, with rows \eqn{F(v) = \{w : v R w\}} and
#' columns \eqn{C(v) = \{w : w R v\}}, and let \eqn{\mathcal{B}(F)} be the set
#' of non-empty intersections of non-empty families of rows, likewise
#' \eqn{\mathcal{B}(C)}. Then \eqn{|\mathcal{B}(F)| = |\mathcal{B}(C)|}.
#' \emph{Proof.} For \eqn{A \subseteq V} let \eqn{A' = \bigcap_{v \in A} F(v)}
#' (with \eqn{\emptyset' = V}) and for \eqn{B \subseteq V} let
#' \eqn{B^* = \{v : B \subseteq F(v)\} = \bigcap_{w \in B} C(w)}. Both maps
#' reverse inclusion and \eqn{A \subseteq A'^*}, \eqn{B \subseteq B^{*\prime}}, so
#' \eqn{A' = A'^{*\prime}} and \eqn{B^* = B^{*\prime *}}; hence \eqn{'} and
#' \eqn{^*} are mutually inverse bijections between the intersections of rows
#' over all \eqn{A}, the intents, and the intersections of columns over all
#' \eqn{B}, the extents, in the terminology of formal concept analysis (Ganter &
#' Wille, 1999), and there are as many of each. \eqn{\mathcal{B}(F)} is the set
#' of intents without \eqn{V}, unless \eqn{V} is a row, and without
#' \eqn{\emptyset}, which is an intent exactly when no column is \eqn{V} (the
#' intersection of all rows is the set of \eqn{w} that are related to every
#' \eqn{v}); symmetrically for \eqn{\mathcal{B}(C)} with rows and columns
#' exchanged. The two corrections are the same two events, so the cardinals
#' agree. The closed forward and backward neighbourhoods are the rows and
#' columns of the reflexive closure of the arc relation, and the engine keeps
#' exactly the non-empty intersections, so \code{forward_base_size} equals
#' \code{backward_base_size} whenever both bases are complete. For the same
#' reason \code{nada_forward_base_gain} equals \code{nada_backward_base_gain}
#' whenever both are defined.
#'
#' \strong{Comparison with the Alexandrov topology.} \eqn{\tau_A \subseteq
#' \tau^+} for every digraph, and the Alexandrov topology of the reversed
#' reachability is contained in \eqn{\tau^-}; both have as many base sets as
#' the digraph has strongly connected components. Each gain is non-negative,
#' because every smallest open set of \eqn{\tau^+} is an intersection of
#' members of the subbase and so belongs to \eqn{B^+}, and \eqn{\tau^+}, being
#' finer, separates at least as many points as \eqn{\tau_A}. The gains count
#' sets of the construction; they do not measure how much finer \eqn{\tau^+}
#' is than \eqn{\tau_A}, since the size of an intersection-closed base depends
#' on the subbase that generates it. On a visibility graph the Alexandrov
#' topology is the chain of \eqn{n} sets \eqn{\{i, \ldots, n\}}, so the gains
#' are \eqn{|B^+| - n}.
#'
#' \strong{Pairwise connectedness.} \eqn{(V, \tau^+, \tau^-)} is pairwise
#' disconnected when \eqn{V} is the union of two disjoint non-empty sets, the
#' first open in \eqn{\tau^+} and the second open in \eqn{\tau^-}. The
#' function decides it exactly from the two subbases, which are always
#' complete, without enumerating either topology. Let \eqn{U^+_x} and
#' \eqn{U^-_x} be the smallest open sets of \eqn{x} in \eqn{\tau^+} and
#' \eqn{\tau^-}, the intersections of the members of each subbase that contain
#' \eqn{x}, and let \eqn{H} be the digraph on \eqn{V} with an arc
#' \eqn{x \to y} when \eqn{y \in U^+_x} or \eqn{x \in U^-_y}. A set \eqn{A} is
#' open in \eqn{\tau^+} with its complement open in \eqn{\tau^-} if and only if
#' no arc of \eqn{H} leaves \eqn{A}: \eqn{A \in \tau^+} means
#' \eqn{U^+_x \subseteq A} for every \eqn{x \in A}, and
#' \eqn{V \setminus A \in \tau^-} means \eqn{U^-_y \subseteq V \setminus A} for
#' every \eqn{y \notin A}, that is, \eqn{x \in A} and \eqn{x \in U^-_y} imply
#' \eqn{y \in A}. A proper non-empty set that no arc leaves exists if and only
#' if \eqn{H} is not strongly connected, and then a strongly connected
#' component that no arc leaves is one; the function takes the first component
#' that Tarjan's (1972) algorithm completes. The smallest open sets cost the
#' intersections of the members that contain each point, \eqn{O(\sum_S |S|^2)}
#' over the members \eqn{S} of the two subbases (expected, since
#' \code{intersect()} hashes), and the search costs \eqn{O(n + a)} for the
#' \eqn{a} arcs of \eqn{H}; with at most \eqn{n} members of at most \eqn{n}
#' points, the total is \eqn{O(n^3)} at worst, and much less when the
#' neighbourhoods are small. The accompanying article
#' decides the property by searching the enumerated topologies (its algorithm
#' 5), with an undecided answer when an enumeration is cut; this criterion
#' gives the same answer whenever that search decides, and never leaves it
#' undecided.
#'
#' \emph{On visibility graphs the answer is known in advance.} When every arc
#' goes from a lower to a higher index, as in every directed visibility graph,
#' and \eqn{n \ge 2}, the space is pairwise disconnected. For each
#' \eqn{k < n}, the final segment \eqn{\{k+1, \ldots, n\}} is the union of the
#' closed out-neighbourhoods of its points, each of which lies inside it, so it
#' is open in \eqn{\tau^+}; in the same way the initial segment
#' \eqn{\{1, \ldots, k\}} is open in \eqn{\tau^-}; and the two segments
#' partition \eqn{V}. On the results of [generate_bitopology()] the check
#' therefore carries no information about the series: it answers
#' \code{FALSE}, with a witness found by the search (the segments
#' \eqn{\{n\}} and \eqn{\{1, \ldots, n-1\}} are always one, but the search
#' can return another). It can answer
#' \code{TRUE} on digraphs with cycles, whose topologies are computed with
#' [generate_topology()].
#'
#' @section Methodological notes:
#' \code{irreversibility_components} and \code{asymmetry_direction} are
#' descriptive statistics of the pair of topologies of one series. By the
#' time-reversal theorem T1 (see [generate_bitopology()]), reading the series
#' backwards with its instants reflected leaves \eqn{I_C} unchanged and
#' changes the sign of \eqn{D}, so both vanish on a palindrome observed on a
#' palindromic grid. Neither proves anything about the reversibility of the
#' process that generated the series, and a positive or negative \eqn{D} is
#' not a prediction of any particular shape of the series. \eqn{I_C} compares
#' counts: two different partitions can have the same number of components.
#'
#' The connected components are exact whether or not a base was truncated;
#' the base sizes and the gains are not reported for a truncated base, because
#' the number of sets found before the cut is only a lower bound. Up to
#' version 0.2.0 the function also returned \code{irreversibility_base}, the
#' normalized difference of the two base sizes, which the theorem above makes
#' identically zero; it was removed in 0.3.0.
#'
#' @section Dependencies:
#' Base R only.
#'
#' @references
#'   Ganter, B., & Wille, R. (1999). Formal concept analysis: Mathematical
#'   foundations. Springer. https://doi.org/10.1007/978-3-642-59830-2
#'
#'   Kelly, J. C. (1963). Bitopological spaces. Proceedings of the London
#'   Mathematical Society, s3-13(1), 71-89. https://doi.org/10.1112/plms/s3-13.1.71
#'
#'   Tarjan, R. (1972). Depth-first search and linear graph algorithms. SIAM
#'   Journal on Computing, 1(2), 146-160. https://doi.org/10.1137/0201010
#'
#' @seealso [generate_bitopology()] for the complete pipeline and theorem T1.
#'
#' @examples
#' g <- horizontal_visibility_graph(c(3, 1, 4, 1, 5, 9, 2, 6), directed = TRUE)
#' tf <- generate_topology(g$out_adjacency, g$n, max_open_sets = 0L)
#' tb <- generate_topology(g$in_adjacency, g$n, max_open_sets = 0L)
#' inv <- bitopology_invariants(tf, tb, g$n)
#' inv$asymmetry_direction
#' inv$forward_base_size == inv$backward_base_size
#'
#' small <- generate_bitopology(c(3, 1, 4))
#' small$invariants$pairwise
#' @export
bitopology_invariants <- function(forward, backward, n_elements,
                                  undirected = NULL, alexandrov = NULL) {
  check_topology_result(forward, "forward")
  check_topology_result(backward, "backward")
  n_elements <- check_count(n_elements, "n_elements", 1L)
  for (side in list(forward, backward)) {
    if (sum(lengths(side$components)) != n_elements) {
      stop("'n_elements' does not match the points covered by the components.",
           call. = FALSE)
    }
  }

  fwd_n_comp <- length(forward$components)
  bwd_n_comp <- length(backward$components)
  fwd_complete <- isTRUE(forward$base_complete)
  bwd_complete <- isTRUE(backward$base_complete)
  fwd_base_size <- if (fwd_complete) length(forward$base) else NA_integer_
  bwd_base_size <- if (bwd_complete) length(backward$base) else NA_integer_

  # Every topology of the engine has at least one point, so the maximum is >= 1
  irreversibility_components <- abs(fwd_n_comp - bwd_n_comp) /
    max(fwd_n_comp, bwd_n_comp)
  asymmetry_direction <- bwd_n_comp - fwd_n_comp

  # --- Pairwise connectedness, decided exactly from the two subbases ---
  pairwise <- pairwise_connectedness(forward$subbase, backward$subbase, n_elements)

  # --- Comparison with the Alexandrov topology ---
  resolution <- NULL
  if (!is.null(alexandrov) && is.list(alexandrov)) {
    alex_base_size <- length(alexandrov$base)
    gain <- function(b) if (is.na(b)) NA_integer_ else b - alex_base_size
    rel <- function(b) if (is.na(b)) NA_real_ else (b - alex_base_size) / max(alex_base_size, 1L)
    resolution <- list(
      alexandrov_base_size = alex_base_size,
      alexandrov_components = length(alexandrov$components),
      alexandrov_connected = isTRUE(alexandrov$connected),
      nada_forward_base_gain = gain(fwd_base_size),
      nada_backward_base_gain = gain(bwd_base_size),
      nada_forward_relative_gain = rel(fwd_base_size),
      nada_backward_relative_gain = rel(bwd_base_size)
    )
  }

  # --- Undirected comparison ---
  undirected_info <- NULL
  if (!is.null(undirected) && is.list(undirected)) {
    computed <- !is.na(undirected$connected)
    undirected_info <- list(
      undirected_components = if (computed) length(undirected$components) else NA_integer_,
      undirected_connected = if (computed) isTRUE(undirected$connected) else NA,
      undirected_base_size = if (isTRUE(undirected$base_complete)) length(undirected$base) else NA_integer_
    )
  }

  list(
    forward_components = fwd_n_comp,
    backward_components = bwd_n_comp,
    forward_connected = isTRUE(forward$connected),
    backward_connected = isTRUE(backward$connected),
    forward_base_size = fwd_base_size,
    backward_base_size = bwd_base_size,
    forward_base_complete = fwd_complete,
    backward_base_complete = bwd_complete,
    irreversibility_components = irreversibility_components,
    asymmetry_direction = asymmetry_direction,
    pairwise = pairwise,
    resolution = resolution,
    undirected_info = undirected_info
  )
}

# A result of generate_topology() with its components computed.
check_topology_result <- function(x, name) {
  if (!is.list(x) || is.null(x$components) || is.null(x$connected)) {
    stop("'", name, "' must be a topology result from generate_topology().",
         call. = FALSE)
  }
  if (is.na(x$connected)) {
    stop("'", name, "' was computed with check_connected = FALSE; its ",
         "components are needed.", call. = FALSE)
  }
  invisible(TRUE)
}
