#' Generate the topology induced by the closed neighbourhoods of a graph
#'
#' @description
#' Builds the topology on the vertices \eqn{\{1, \ldots, n\}} of a graph that is
#' generated by the closed neighbourhoods \eqn{N[v] = \{v\} \cup N(v)}, computes
#' its connected components exactly, and optionally enumerates its open sets.
#' Given undirected adjacency lists it is the undirected construction; given the
#' out-neighbour or in-neighbour lists of a digraph it gives the forward or the
#' backward topology. Use it directly for any graph, or through
#' [generate_bitopology()] for time series.
#'
#' @param adjacency List of length \code{n_elements}; element \code{i} is an
#'   integer vector with the 1-based indices of the neighbours (for a directed
#'   construction, the out-neighbours or the in-neighbours) of vertex \code{i}.
#'   Repeated indices, \code{i} itself and indices outside
#'   \eqn{1, \ldots, n} are ignored. No default.
#' @param n_elements Integer scalar, at least 1: the number of vertices. Must
#'   equal \code{length(adjacency)}. No default.
#' @param max_open_sets Non-negative integer scalar (default 1,000,000). The
#'   enumeration of the open sets stops as soon as their number exceeds it;
#'   \code{0} skips the enumeration.
#' @param max_base_sets Positive integer scalar (default 100,000). The closure
#'   of the subbase under intersections stops at the first new intersection
#'   that makes the base exceed this number of sets. It is not a strict cap on
#'   the size of the returned base: the whole subbase is always kept, and so is
#'   the intersection that crosses the limit.
#' @param check_connected Logical scalar (default \code{TRUE}): whether to
#'   compute the connected components.
#' @param verify_axioms Logical scalar (default \code{FALSE}): whether to check,
#'   independently of the construction, that the enumerated family contains
#'   the empty set and the whole set and is closed under the union and the
#'   intersection of any two members, which on a finite set are the axioms of
#'   a topology. The check runs only when \code{topology_complete} is
#'   \code{TRUE}; it takes \eqn{O(|\tau|^2 \lceil n/64 \rceil)} word
#'   operations and \eqn{O(|\tau|^2)} hash lookups.
#' @return A \code{list} with:
#'   \describe{
#'     \item{subbase}{List of integer vectors: the distinct closed
#'       neighbourhoods \eqn{N[v]}.}
#'     \item{base}{List of integer vectors: the distinct non-empty finite
#'       intersections of members of the subbase. When \code{base_complete} is
#'       \code{FALSE} it is a subfamily that contains the whole subbase.}
#'     \item{base_complete}{Logical: whether the intersection closure finished
#'       within \code{max_base_sets}.}
#'     \item{connected}{Logical: whether the space is connected; \code{NA} if
#'       \code{check_connected = FALSE}.}
#'     \item{components}{List of integer vectors: the connected components,
#'       exact whether or not the base is complete (see Methodological notes);
#'       an empty list if \code{check_connected = FALSE} and \eqn{n \ge 2}.}
#'     \item{iterations_base}{Integer: rounds of the intersection closure.}
#'     \item{topology}{List of integer vectors with the enumerated open sets,
#'       or \code{NULL} if \code{max_open_sets = 0}.}
#'     \item{n_open_sets}{Integer: the number of enumerated open sets, or
#'       \code{NA} if the enumeration was not requested.}
#'     \item{topology_complete}{Logical: \code{TRUE} if the enumerated family
#'       is the whole topology; \code{FALSE} if the enumeration was requested
#'       but cannot be certified complete, because \code{max_open_sets} cut it
#'       or because the base was incomplete; \code{NA} if the enumeration was
#'       not requested.}
#'     \item{iterations_topo}{Integer: rounds of the union closure.}
#'     \item{axioms_ok}{Logical, present only when \code{verify_axioms = TRUE}
#'       and \code{topology_complete} is \code{TRUE}.}
#'     \item{axiom_failure}{Character, present only if that check fails.}
#'   }
#'
#' @details
#' The base is computed by wavefront propagation: each new intersection is
#' intersected, in the next round, with every set already in the base, until a
#' round produces nothing new. Every new set is a proper subset of a set
#' produced in the previous round, so the closure ends after at most \eqn{n}
#' rounds; the base itself can have exponentially many sets in \eqn{n}, which
#' is what \code{max_base_sets} guards against. The components are computed
#' from the signatures \eqn{S(x) = \{B \in \mathcal{B} : x \in B\}}: \eqn{x}
#' and \eqn{y} are comparable when \eqn{S(x) \subseteq S(y)} or
#' \eqn{S(y) \subseteq S(x)}, and the components are those of the
#' comparability graph, found by breadth-first search in
#' \eqn{O(n^2 \lceil |\mathcal{B}| / 64 \rceil)} word operations. The open sets
#' are enumerated by the same wavefront scheme with unions, which can produce
#' up to \eqn{2^n} sets; when the space is already known to be disconnected,
#' the engine warns that the enumeration is not needed for connectivity.
#'
#' @section Methodological notes:
#' \emph{Closed neighbourhoods.} Nada, El Atik and Atef (2018, Definition 3.1)
#' take as subbase the post classes of the adjacency relation, which for a
#' loopless graph are the open neighbourhoods \eqn{N(v)}. This function uses the
#' closed neighbourhoods \eqn{N[v]}, so that every vertex lies in its own
#' subbase element: the subbase covers the vertex set and the smallest open set
#' containing \eqn{v} is contained in \eqn{N[v]}. The two constructions give
#' different topologies; on the complete graph, for instance, the closed
#' variant gives the indiscrete topology and the open one the discrete
#' topology.
#'
#' \emph{Why the components are exact, even from a truncated base.} In a finite
#' space every point \eqn{x} has a smallest open set \eqn{U_x}, the
#' intersection of the members of the subbase that contain \eqn{x}. For any
#' family \eqn{F} with subbase \eqn{\subseteq F \subseteq \tau}, every member of
#' \eqn{F} that contains \eqn{x} contains \eqn{y} if and only if
#' \eqn{y \in U_x}: if \eqn{y \in U_x}, every open set containing \eqn{x}
#' contains \eqn{U_x}; conversely, the members of the subbase that contain
#' \eqn{x} are among those of \eqn{F}, and their intersection is \eqn{U_x}. The
#' relation \eqn{x \le y \iff y \in U_x} is the specialization preorder.
#' Let \eqn{\sim} be the equivalence generated by comparability. Each class
#' \eqn{C} is open, because it contains \eqn{U_x} for each of its points (every
#' \eqn{y \in U_x} satisfies \eqn{x \le y}), and closed, because its complement
#' is a union of other classes; so every connected component lies inside one
#' class. Each class is connected: if a class split into two non-empty parts
#' \eqn{A} and \eqn{B}, both relatively open, some \eqn{x \in A} and
#' \eqn{y \in B} would be comparable, say \eqn{x \le y}; the open set that cuts
#' out \eqn{A} contains \eqn{U_x}, hence \eqn{y}, a contradiction (the case
#' \eqn{y \le x} is symmetric). The components are therefore the classes, and
#' since the engine places the whole subbase in the base before the closure
#' can be cut, the signatures it compares always give the same classes.
#'
#' \emph{What the base size measures.} The number of sets in the base is a
#' property of the construction, not of the topology: two subbases that
#' generate the same topology can have intersection closures of different
#' sizes.
#'
#' @section Dependencies:
#' The compiled engine (C++ through 'Rcpp').
#'
#' @references
#'   Nada, S., El Atik, A. E. F., & Atef, M. (2018). New types of topological
#'   structures via graphs. Mathematical Methods in the Applied Sciences,
#'   41(15), 5801-5810. https://doi.org/10.1002/mma.4726
#'
#' @seealso [generate_bitopology()] for the time-series pipeline,
#'   [generate_alexandrov_topology()] for the Alexandrov topology of
#'   reachability, [is_topology_connected_exact()] for an enumerated topology,
#'   and the user manual in \code{system.file("manuals", package = "topologyR")}.
#'
#' @examples
#' g <- horizontal_visibility_graph(c(3, 1, 4, 1, 5))
#' topo <- generate_topology(g$adjacency, g$n, max_open_sets = 0L)
#' topo$connected
#' topo$components
#' topo$topology_complete
#'
#' full <- generate_topology(g$adjacency, g$n, verify_axioms = TRUE)
#' full$n_open_sets
#' full$topology_complete
#' full$axioms_ok
#' @export
generate_topology <- function(adjacency, n_elements,
                              max_open_sets = 1000000L,
                              max_base_sets = 100000L,
                              check_connected = TRUE,
                              verify_axioms = FALSE) {
  if (!is.list(adjacency)) {
    stop("'adjacency' must be a list of integer vectors.", call. = FALSE)
  }
  n_elements <- check_count(n_elements, "n_elements", 1L)
  if (length(adjacency) != n_elements) {
    stop("Length of 'adjacency' must equal 'n_elements'.", call. = FALSE)
  }
  max_open_sets <- check_count(max_open_sets, "max_open_sets", 0L)
  max_base_sets <- check_count(max_base_sets, "max_base_sets", 1L)
  enumerate <- max_open_sets > 0L

  generate_topology_engine(
    adjacency = adjacency,
    n_elements = n_elements,
    max_open_sets = max_open_sets,
    max_base_sets = max_base_sets,
    enumerate_topology = enumerate,
    check_connected = check_connected,
    verify_axioms = verify_axioms
  )
}


#' Connectedness of a fully enumerated topology
#'
#' @description
#' Decides whether a finite topological space, given by the complete list of
#' its open sets, is connected: it is connected if and only if no proper
#' non-empty open set has an open complement. Use it on the \code{topology}
#' element of a result whose \code{topology_complete} is \code{TRUE}; for a
#' topology given by a subbase, [generate_topology()] returns the components
#' without enumerating anything.
#'
#' @param topology List of integer vectors: the open sets of a topology on
#'   \eqn{\{1, \ldots, n\}}, in any order, possibly repeated. Indices outside
#'   that range are ignored. No default.
#' @param n_elements Integer scalar, at least 1: the number of points. No
#'   default.
#' @return A \code{list} with \code{connected} (logical). When it is
#'   \code{FALSE}, also \code{component1}, a proper non-empty open set whose
#'   complement is open, and \code{component2}, that complement (integer
#'   vectors). Each of the two is a union of connected components, not
#'   necessarily a single component; the field names are kept from earlier
#'   versions.
#'
#' @details
#' Each set is encoded as a bitset and stored in a hash set; the function scans
#' the open sets once and looks up each complement, in
#' \eqn{O(|\tau| \lceil n/64 \rceil)} word operations when the hash spreads
#' the sets evenly over the table (the usual uniform-hashing assumption; a
#' fixed hash function gives no worst-case guarantee).
#'
#' @section Methodological notes:
#' The function does not check that the list is a topology, that is, that it
#' contains the empty set and the whole set and is closed under unions and
#' intersections. On an arbitrary family it reports whether some proper
#' non-empty member has its complement in the family, which is connectedness
#' only when the family is the complete topology.
#'
#' @section Dependencies:
#' The compiled engine (C++ through 'Rcpp').
#'
#' @seealso [generate_topology()] for exact components from a subbase.
#'
#' @examples
#' chain <- list(integer(0), 1L, 1:2, 1:3)
#' is_topology_connected_exact(chain, 3L)
#'
#' split <- list(integer(0), 1:2, 3:4, 1:4)
#' is_topology_connected_exact(split, 4L)
#' @export
is_topology_connected_exact <- function(topology, n_elements) {
  if (!is.list(topology)) {
    stop("'topology' must be a list of integer vectors.", call. = FALSE)
  }
  n_elements <- check_count(n_elements, "n_elements", 1L)

  topology <- lapply(topology, as.integer)
  is_connected_exact_cpp(topology, n_elements)
}
