#' topologyR: topologies of graphs and bitopologies of time series
#'
#' @description
#' The package turns a graph into the topology generated by the closed
#' neighbourhoods of its vertices and computes its connected components
#' exactly, without enumerating the topology. For time series it builds the
#' horizontal and natural visibility graphs, at equally or unequally spaced
#' instants and with a natural criterion decided exactly under IEEE 754 double
#' arithmetic, and from their directed
#' versions the forward and backward topologies, a bitopological space, with
#' the Alexandrov topology of reachability and the invariants of the pair.
#'
#' @section Main functions:
#' [horizontal_visibility_graph()] and [natural_visibility_graph()] build the
#' graphs; [generate_topology()] builds a topology of closed neighbourhoods
#' from any adjacency lists; [generate_alexandrov_topology()] builds the
#' Alexandrov topology of any digraph; [generate_bitopology()] runs the whole
#' pipeline for a series and states the time-reversal theorem;
#' [bitopology_invariants()] reports the invariants of a forward-backward
#' pair; [time_reverse()] reverses a series together with its instants. The
#' proofs of the results the package relies on are written in the help pages
#' that state them, those of the exact natural criterion in
#' [natural_visibility_exactness]. The user manual is in
#' \code{system.file("manuals", "user_manual.pdf", package = "topologyR")}.
#'
#' @keywords internal
#' @aliases topologyR-package
"_PACKAGE"

#' @useDynLib topologyR, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL
